cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

zoo/urls.py
"""
Definition of urls for zoo.
"""
from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^orders/', include(('orders.urls', 'order'), namespace='orders')),
    url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^login/$',
        django.contrib.auth.views.LoginView,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Вход',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.LogoutView,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    
     url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += staticfiles_urlpatterns()

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/base.html
{% extends "app/layout.html" %} 
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Корзина{% endif %}
{% endblock %}
{% block content %}
<!-♕ -->
<div class="jumbotron">
    <body id="bg" style="background-image: url('{% static "images/123.jpg"%}')";>
    <style>
   div {
    background-image: url(../../static/app/content/123.jpg);
    background-size:cover;
    background-attachment: fixed;
        }
        </style>
    <div class="cart">
        {% if user.is_authenticated %}
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Ваша корзина:
                <a href="{% url "cart:cart_detail" %}">
                    {{ total_items }} Товар(a) {{ total_items|pluralize }},
                   {{ cart.get_total_price }}Рублей
                </a>
            {%  else %}
                Корзина пуста.
            {% endif %}
        {% endwith %}
        {% endif %}
    </div>
</div>
  <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Зоомагазин Филя</p>
        </footer>
    </div>
{% endblock %}

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
<!-♕ -->
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
<body>
    <style>
        body {
             background-image: url(../../static/app/content/123.jpg); 
    background-attachment: fixed;
    background-size:cover;
    background-attachment: fixed;
        }
    </style>
<div class="main">
    <div class="jumbotron">
        <h1>Ваша корзина</h1>
        <style>
            th { 
                text-align:center;
            }
        </style>
        <table width="100%" border="7" cellpadding="7">
   <tr align="justify" valign="middle" bordercolor="#000" bgcolor="fff" text-align="center">
    
   
            <thead>
            <tr>
                
               <th>Фото</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена за единицу</th>
                <th>Итог</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td valign="top" align="center">
                            <a >
                               <img src="{{ product.image.url }}" width="100" />
                            </a>
                        
                        <td valign="middle" align="center">{{ product.name }}</td>
                        <td valign="middle" align="center">{{ item.quantity }}</td>
                        <td valign="middle" align="center"><a href="{% url "cart:cart_remove" product.id%}">Удалить товар</a></td>
                        <td valign="middle" align="center" class="num">{{ item.price }}Руб</td>
                        <td valign="middle" align="center" class="num">{{ item.total_price }}Руб</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td valign="middle" align="center">Всего</td>
                <td valign="middle" align="center" colspan="4"></td>
                <td valign="middle" align="center" class="num">{{ cart.get_total_price }}Рyблей</td>
            </tr>
            </tbody>
            
  </table>
        
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="button light">Продолжить покупки</a>
            <a href="{% url "orders:order_create" %}" class="button">
                Оформить заказ
            </a>
        </p>
    </div>
</div>
    </body>
{% endblock %}